/* ----- Global Imports ----- */ 
import { ClerkProvider, UserButton, auth, currentUser, clerkClient, getAuth } from "@clerk/nextjs";
import Link from "next/link";
import GameContextProvider from "@/context/game-context";

import "./globals.css";

export const metadata = {
  title: "Wordle by the Lads",
  description: "Generated by Wordle Team Legends",
};

export default async function RootLayout({ children }) {

  const { userId } = auth();
  const user = await currentUser();

  return (
    <ClerkProvider>
    <html lang="en">
      <GameContextProvider>
        <body>
          {userId && <UserButton afterSignOutUrl="/" userProfileMode="navigation" userProfileUrl="/user-profile" />}
          {!userId && <Link href="/sign-in">Sign In</Link>}
          {children}
        </body>
      </GameContextProvider>
    </html>
    </ClerkProvider>
  );
};
