/* ----- Global Imports ----- */ 
import { ClerkProvider, UserButton, auth, currentUser, clerkClient, getAuth } from "@clerk/nextjs";
import Link from "next/link";
import GameContextProvider from "@/context/game-context";
import LoginManager from "@/components/loginmanage";
import './globals.css';

export const metadata = {
  title: "Wordle by the Lads",
  description: "Generated by Wordle Team Legends",
};

export default async function RootLayout({ children }) {

  const { userId } = auth();
  const user = await currentUser();

  return (
    <ClerkProvider>
    <html lang="en">
      <GameContextProvider>
        <body>
         <LoginManager/>
         <nav>
              <Link href="/">Home</Link>
              <Link href="/play">Play</Link>
            </nav>
          {children}
          <footer className="footer">
        <p>© 2024 Wordly Game. All rights reserved.</p>
      </footer>
        </body>
      </GameContextProvider>
    </html>
    </ClerkProvider>
  );
};
