
export const metadata = {
  title: "Wordle by the Lads",
  description: "Generated by Wordle Team Legends",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
