/* ----- Third Party Imports ----- */
import { ClerkProvider } from "@clerk/nextjs";

/* ----- Project Imports ----- */
import "./login.css";

export const metadata = {
  title: "Wordle by the Lads",
  description: "Generated by Wordle Team Legends",
};

export default function RootLayout({ children }) {

  return (
    <ClerkProvider>
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
};
